import colorama
colorama.init()
start = "\033[1;31m"
end = "\033[0;0m"
print (" " + start + "" + end)

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'
NW = 'Restoration and Renovation of Bhagabat Tungi at Kaudiamunda'
EC = 100000
HA = 'M.L.A.L.A.D(2013-14)'







if __name__ == "__main__":
    


    print('\n\t\t\t\t\tDETAILED ESTIMATE')
    print('\n\n\t\t\t\t\tGOVERNMENT OF ODISHA')
    print('\n\n\t\t\t\t      PANCHAYATIRAJ DEPARTMENT')
    print('\n\n\t\t\t\t\tSUBARNAPUR DISTRICT')
    print('\n\n\t\t\t\t\tPANCHAYAT SAMITI BINKA')
    print('\n\nName of the work:- ',NW,'\n')
    print('Estimated Cost:-','Rs.{:.2f}'.format(EC))
    print('\nHead of Account:-',HA)
    
    
    
    
    
    